name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main  

permissions:
  id-token: write   
  contents: read   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OIDC authentication
        id: oidc
        run: echo "GITHUB_ID_TOKEN=${{ steps.oidc.outputs.token }}" >> $GITHUB_ENV

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/"  
          api_location: ""  
          output_location: "dist/essentials"  # The output directory of the build
          github_id_token: ${{ env.GITHUB_ID_TOKEN }}
